"""empty message

Revision ID: a595170830d0
Revises: 53cdd05d3672
Create Date: 2020-11-08 15:17:26.920487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a595170830d0'
down_revision = '53cdd05d3672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tbl', sa.Column('name', sa.String(length=15), nullable=True))
    op.add_column('user_tbl', sa.Column('password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tbl', 'password')
    op.drop_column('user_tbl', 'name')
    # ### end Alembic commands ###
